dna = 'AGGATCGCCGTCGAGGTCTGGAAGGCGTTGGTCGTGGATGGTGCCGAGCCGATATGCACGGTGTGTAGATGGTCGGATATGATCGCACACGAGAAAGCAGACTGGCGTAGGGAAACTACGCTGGCCTCTGGTCCACAGGCATTACGGTATCGCAAGCCCGTTGGTGCGATTCTGATGTTTGGTTCTATTTGTCTATATCGTTCGATACGACGACCTCGCGGTCGCGCGTGCCTCACTGTGCGCCAACCCGGTTATTCAAGATTGTTTAGTCACAACGTCTGGTATGGAGGCCCTAAGGCGAAATGTGAATTGTTTATTCTCGGACTGACACGAGGTTGGTATCTAGCCGTAGGGCAGTTGATGGCGCAGTATCCAACACTGCCTTTGATGATGTTGGGTCATAATCATAACTTAAGTTTGGCTGCAGAACTCTGACTGTAGGGTAAACACATAGCGACATGACGATTGCGCACCAGCGTTGTTACTGGGTGTTATAGTCAAAGGGTCTCAACACTTTAGTACACCCGGTAATCTACCCTATAGCGAGCAGATCCCAAACGGCGGCAAGGCCGGGATCGCAGCGGTTATAGATGTAGTAGGATCACATCCAATTAGGGTTGGCAAGTGGAATAAGGATTGGGTTACAGACCGAAACGGATATGGCCATCTAGTTACATCTGTCCAACTCCGCGTACTCGTGCGTCTCCCTTAATCGCTAATCGTGTTTGTGATCGAACCAACCTATTCGTAGTTGGGCTCTTCCTCGGGTTAGTAACCCAGGTAAAGAGTAGGGGAAAATCGTCTTCGTATTTTACTGATGCCCCATACTGCCATA'
comp = ''
rcomp = ''
for char in dna:
    if char == 'A':
        comp += 'T'
    if char == 'T':
        comp += 'A'
    if char == 'C':
        comp += 'G'
    if char == 'G':
        comp += 'C'
for char in comp:
    if char == 'A':
        rcomp = 'A' + rcomp
    if char == 'T':
        rcomp = 'T' + rcomp
    if char == 'C':
        rcomp = 'C' + rcomp
    if char == 'G':
        rcomp = 'G' + rcomp
print (rcomp)
